### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by bbatha** [facebookincubator/fastmod#1]
The documentation states:

> fastmod is supported on macOS and Linux.

Is there a reason for this support policy? I tested out fastmod on windows and it seems to work fine. I also skimmed the code base for any unixisms and the only one I could find was assuming `$EDITOR` was set/defaulting to vim.

**Comment by swolchok** [comment]
I'm glad it works fine! The reason is just that nobody had asked for Windows support yet (congratulations on being the first) and I personally don't use Windows for work. I'd be happy to consider pull requests fixing Windows-specific issues and to consider Windows "supported" if there is enough demand.

Regarding the issue with `$EDITOR`, I'm not sure what the equivalent Windows convention is. Can you fill me in on that?

The only other question I have is whether the colored output via the `term` crate works OK on Windows. Does it?

**Comment by swolchok** [comment]
> The vast majority of workflow in Windows assumes the presence of its baked-in graphical toolchain and file associations with your favorite editor a la Gnome's "Default Applications"

Would defaulting to `start` be a reasonable choice?

> term also notably has a memory leak on Windows right now. 

IMO the correct solution to this is to fix `term`. I'd be interested in doing that eventually, perhaps on my personal Windows machine, but my personal life is quite busy right now. I might be able to take a look at it in a few weeks.

> clearing the screen, which AFAIK there's not an awesome library to support it yet

I couldn't find a Rust terminal library I was completely thrilled with for purposes of porting codemod's terminal module. codemod just wants you to support ncurses and get out of its way, and the fancier terminals really get in the way of that. If there's a terminal crate that I missed that supports all the operations we need itself, I wouldn't mind switching; I just don't want to end up with a patchwork of crates in order to add Windows support.

**Comment by ErichDonGubler** [comment]
> Would defaulting to `start` be a reasonable choice?

Absolutely. :) Wish I'd thought of that first!

> I just don't want to end up with a patchwork of crates in order to add Windows support.

I don't know of a cross-platform one that supports clearing the screen yet... **sigh**. :\ Which is not to say that one isn't out there for sure -- but there's not a popular one AFAIK.

**Comment by bbatha** [comment]
> The only other question I have is whether the colored output via the term crate works OK on Windows. Does it?

I can't speak to the general quality but I get red and green text in conhost terminals (cmd/powershell) on Windows 7.

**Comment by swolchok** [comment]
Just to give an update, I think we should probably try `$EDITOR` then `vim` then `notepad` then `start`, but I want to see if that will work well for all of 1) vanilla cmd.exe 2) Powershell 3) Windows Subsystem for Linux. The other issue with `start` is that it's presumably not going to block until the edit is done, and that probably won't result in a good user experience. I'm not sure if that's going to be an issue with `notepad` as well.

**Comment by ErichDonGubler** [comment]
`notepad` blocks, but `start` does not unless one uses `start "" /B /W <command...>`. However, many editor executables in Windows are stubs that kick off async processes...which unfortunately defeats even a blocking `start`. 😕 

On another note, `notepad` should *ALWAYS* be present on Windows machines, so I don't think designing a fallback for it is valid.

**Comment by swolchok** [comment]
I also forgot to mention that 2502ae105450412be0fa8b28410df5368072d18e landed yesterday. It makes fastmod fall back to notepad.exe on Windows if `EDITOR` and `vim` are not working.

**Comment by swolchok** [comment]
768e8cf02a0a69b3385f2de6c013bf4611022389 has landed.
