### ISSUE TITLE
1.0 release timing?

### ISSUE THREAD

**Issue by castastrophe** [facebookincubator/fastmod#43]
👋 Hello! This is a very exciting project. What is your timeline for releasing this at a 1.0 version? We're evaluating this for use on large-scale projects and would prefer to utilize a stable tool that is production ready. Not to mention semver before a 1.x can be a headache.

If there is anything I can do to help, I'm happy to contribute as well so don't hesitate to reach out.

**Comment by swolchok** [comment]
I have no particular timeline for a 1.0 version. Reviewing the semver guidelines for when 1.0 is appropriate, we are probably past that point; I am hesitant to actually do a 1.0 release because it would not come with a commitment to increase the commit velocity of fastmod beyond what it is currently (e.g., there were less than a dozen commits to fastmod in 2022, and 4 of those were automated).

> stable tool

see low commit velocity above

> production ready

I'm not sure what this entails in the context of a primarily-loosely-interactive find/replace tool. It's been used for some big changes.
